// JS re-export shim — see products.ts for the real implementation.
export {
  countProducts,
  createProduct,
  incrementProductPurchase,
  incrementProductView,
  listLowStockProducts,
  setProductStatus,
  setProductsStatus,
  listBrands,
  deleteProductById,
  deleteProductsByIds,
  findProductById,
  findProductBySku,
  findProductBySlug,
  listFeaturedProducts,
  listProductFacets,
  listProductsByIds,
  listProducts,
  listProductsByCategoryId,
  slugExists,
  updateProduct,
} from "./products.ts";
