// JS re-export shim — see orders.ts for the real implementation.
export {
  buildCanonicalAddress,
  buildCheckoutFromCart,
  buildCheckoutFromItems,
  bulkSetOrderStatus,
  cancelOrder,
  createCodOrder,
  createHttpError,
  createOrderFromCheckout,
  creditReferralIfFirstOrder,
  findPaidOrderByPaymentId,
  getAllOrdersForRoute,
  getCouponDiscount,
  getOrderByIdForUser,
  getUserOrders,
  normalizeCheckoutItems,
  normalizeShippingAddressInput,
  notifyOrderConfirmation,
  restoreStockForOrder,
  roundMoney,
  updateOrderStatus,
} from "./orders.ts";
