// JS re-export shim — see products.ts for the real implementation.
export {
  bulkDeleteProducts,
  bulkSetProductStatus,
  createProductRecord,
  deleteProductRecord,
  restoreProductRecord,
  getAllProducts,
  getCatalogFacets,
  getFeaturedProducts,
  getProductBrands,
  getProductByCategoryId,
  getProductByCategoryName,
  getProductByExactRating,
  getProductBySlugValue,
  getProductByPriceRange,
  getProductCount,
  getSingleProduct,
  getProductBySubCategoryId,
  getProductBySubCategoryName,
  getProductByThirdSubCategoryId,
  getProductByThirdSubCategoryName,
  updateProductRecord,
  updateProductQuickAction,
} from "./products.ts";
